version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: course_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"